# Generated by Django 4.2.11 on 2024-11-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_products_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
