# Generated by Django 4.2.11 on 2024-10-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sales_created_at_sales_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='sales',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
