# Generated by Django 4.1 on 2024-11-27 04:12

from django.db import migrations, models


def actualizar_fechas(apps, schema_editor):
    modelo = apps.get_model('sales', 'Sales')
    for objeto in modelo.objects.all():
        try:
            nueva_fecha = objeto.created.strftime('%Y-%m-%d')
            objeto.sale_date = nueva_fecha
            objeto.save()
        except ValueError:
            print(f"Error al procesar la fecha: {objeto.sale_date}")


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_sales_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="sales",
            name="sale_date",
            field=models.DateField(null=True),
        ),
        migrations.RunPython(actualizar_fechas)
    ]
