# Generated by Django 4.2.11 on 2024-10-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='presentation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
